export { default as IndexPage } from './_index'
export { default as ProjectPage, ChapterPage, SectionPage } from './project2025'
export { default as AboutPage} from './about'
export { default as ContributePage } from './contribute'
export { default as FaqPage } from './faq'
export { default as TermsAndConditionsPage } from './terms-and-conditions'
export { default as PrivacyPolicyPage } from './privacy-policy'
export { default as ResourcesPage } from './resources'
